apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: native-instruments
spec:
  clusterIP: x.x.x.x
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-2
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 443
  - name: port-3
    nodePort: 30901
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: port-4
    nodePort: 30943
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
