apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    run: nginx
  name: nginx
  namespace: native-instruments
spec:
  minReadySeconds: 20
  progressDeadlineSeconds: 600
  replicas: 15
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - env:
        - name: nginx
          value: nginx
        image: [PRIVATE_REG]/native-instruments/nginx:[VERSION]
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/nginx
          name: nginx-logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: test-credit
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: native-instruments-servers
        operator: Exists
      volumes:
      - emptyDir: {}
        name: nginx-logs
status: {}
