apiVersion: v1
kind: Service
metadata:
  labels:
    run: application
  name: application
  namespace: native-instruments
spec:
  clusterIP: x.x.x.x
  ports:
  - name: tomcat
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: application
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
