apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    run: application
  name: application
  namespace: native-instruments
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: application
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: application
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8080"
        - name: MONGODB_URI
          value: mongodb://[USERNAME]:[PASSWORD]@[MONGO_IP_PRIMARY]:27017,[MONGO_IP_SECONDARY]:27017/meta?replicaSet=test-rs&authSource=[USERNAME]&readPreference=secondaryPreferred
        image: hello-world
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: application
        readinessProbe:
          failureThreshold: 55
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - mongo-native-instruments
        ip: [IP]
      - hostnames:
        - mongo-native-instruments-n2
        ip: [IP]
      - hostnames:
        - mongo-native-instruments-arb
        ip: [IP]
      imagePullSecrets:
      - name: native-instruments-credit
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: native-instruments-servers
        operator: Exists
status: {}
